dbtest/config/routes.rb
Rails.application.routes.draw do
  resources :memos

end

dbtest/app/models/memo.rb
class Memo < ActiveRecord::Base
end

dbtest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dbtest/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:student_name, :student_id, :student_academy, :student_major, :student_degree, :student_credit, :student_course, :student_password)
    end
end

dbtest/app/helpers/application_helper.rb
module ApplicationHelper
end

dbtest/app/helpers/memos_helper.rb
module MemosHelper
end

dbtest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dbtest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dbtest/app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :student_academy %><br>
    <%= f.text_field :student_academy %>
  </div>
  <div class="field">
    <%= f.label :student_major %><br>
    <%= f.text_field :student_major %>
  </div>
  <div class="field">
    <%= f.label :student_degree %><br>
    <%= f.text_field :student_degree %>
  </div>
  <div class="field">
    <%= f.label :student_credit %><br>
    <%= f.number_field :student_credit %>
  </div>
  <div class="field">
    <%= f.label :student_course %><br>
    <%= f.text_field :student_course %>
  </div>
  <div class="field">
    <%= f.label :student_password %><br>
    <%= f.text_field :student_password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dbtest/app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

dbtest/app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memos</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Student id</th>
      <th>Student academy</th>
      <th>Student major</th>
      <th>Student degree</th>
      <th>Student credit</th>
      <th>Student course</th>
      <th>Student password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.student_name %></td>
        <td><%= memo.student_id %></td>
        <td><%= memo.student_academy %></td>
        <td><%= memo.student_major %></td>
        <td><%= memo.student_degree %></td>
        <td><%= memo.student_credit %></td>
        <td><%= memo.student_course %></td>
        <td><%= memo.student_password %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

dbtest/app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

dbtest/app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @memo.student_name %>
</p>

<p>
  <strong>Student id:</strong>
  <%= @memo.student_id %>
</p>

<p>
  <strong>Student academy:</strong>
  <%= @memo.student_academy %>
</p>

<p>
  <strong>Student major:</strong>
  <%= @memo.student_major %>
</p>

<p>
  <strong>Student degree:</strong>
  <%= @memo.student_degree %>
</p>

<p>
  <strong>Student credit:</strong>
  <%= @memo.student_credit %>
</p>

<p>
  <strong>Student course:</strong>
  <%= @memo.student_course %>
</p>

<p>
  <strong>Student password:</strong>
  <%= @memo.student_password %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>